[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on   = [ "g", "m" ]
run  = "plugin mount-tabs"
desc = "Open all mount points in tabs"

[[mgr.prepend_keymap]]
on   = [ "M" ]
run  = "plugin mount"
desc = "Open mount/unmount menu"
