# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostName = "garnix"; # Define your hostname.

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
	"/" = { 
		device = "/dev/disk/by-uuid/7b9472ca-32ee-4fc6-8fe3-c851aec509ab";
      		fsType = "btrfs";
      		options = [ "subvol=root" "compress=zstd" ];
    	};

  	"/home" = { 
		device = "/dev/disk/by-uuid/7b9472ca-32ee-4fc6-8fe3-c851aec509ab";
 		fsType = "btrfs";
 		options = [ "subvol=home" "compress=zstd" ];
 	};

 	"/nix" = { 
		device = "/dev/disk/by-uuid/7b9472ca-32ee-4fc6-8fe3-c851aec509ab";
 		fsType = "btrfs";
 	  	options = [ "subvol=nix" "compress=zstd" "noatime" ];
 	};

 	"/boot" = { 
		device = "/dev/disk/by-uuid/D456-E391";
 		fsType = "vfat";
 		options = [ "fmask=0022" "dmask=0022" ];
 	};
	"/swap" = {
		device = "/dev/nvme0n1p2";
		fsType = "swap";
		options = [ "noatime" ];
	};
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
